### ISSUE TITLE
Recommendation of the best way to obtain the ILogger when using LogFileLoadExceptions

### ISSUE THREAD

**Issue by eobeda** [shaynevanasperen/Code#4]
Hi,

Looking to use both LogFileLoadExceptions and LogChanges in an .Net 5 Asp.Net project.  I believe the code should be compatible with the newer runtime, but having troubles determining how to obtain the ILogger instance.

The ConfigureAppConfiguration method does appear to pass a service instance, so my 'default' technique
`Services.GetService<ILogger<Program>>();`
doesn't work. Any suggestions ?

``` CSharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                  // Using the default config  object in the sample
                    config.LogFileLoadExceptions((type) =>
                    {
                        return null;  <=== HERE
                    });
```

Thanks in advance for the help
Ed
ps: Double check that I am using it correctly :).

**Comment by shaynevanasperen** [comment]
This is a good question!

In my projects, I've realized that I needed to have access to a logger before the application has fully started up, so that if something goes wrong during startup it can be logged. Unfortunately the framework doesn't guide us towards doing this and it isn't obvious how this should be achieved, so I've invented my own way. What we need to do is create a logger inside our application's `Main` method, and then refer to that. For this purpose, I've actually created a little class that lets me access a global static logger that's configured the same way as the one that will be supplied via IoC to the rest of the application once it has started up. Here's an example of one I made that uses `Serilog` under the hood:
```cs
public static class GlobalSerilog
{
    public static void Configure(
        IConfiguration? configuration = null,
        Action<string, LoggerConfiguration>? configureLogSinksForPath = null,
        CancellationToken cancellationToken = default)
    {
        Log.CloseAndFlush();
        Log.Logger = new LoggerConfiguration()
            .Configure() // See this call to configure is repeated in Program.cs
            .CreateLogger();

        if (cancellationToken.CanBeCanceled)
            cancellationToken.Register(Log.CloseAndFlush);
    }

    public static readonly ILoggerFactory Factory = new LoggerFactory();

    public static Microsoft.Extensions.Logging.ILogger GetLogger<T>() => GetLogger(typeof(T));

    public static Microsoft.Extensions.Logging.ILogger GetLogger(Type type) => GetLogger(type.FullName);

    public static Microsoft.Extensions.Logging.ILogger GetLogger(string? categoryName = "") => LoggerProvider.CreateLogger(categoryName);

    public static void Shutdown() => Log.CloseAndFlush();

    static readonly ILoggerProvider LoggerProvider = new SerilogLoggerProvider();

    class LoggerFactory : ILoggerFactory
    {
        const string ErrorMessage = "This LoggerFactory is not intended to be used for configuring the logging system.";

        public Microsoft.Extensions.Logging.ILogger CreateLogger(string categoryName) => LoggerProvider.CreateLogger(categoryName);

        public void AddProvider(ILoggerProvider provider) => throw new InvalidOperationException(ErrorMessage);

        public void Dispose() => throw new InvalidOperationException(ErrorMessage);
    }

    public static LoggerConfiguration Configure(this LoggerConfiguration configuration) =>
        configuration
            .MinimumLevel.Information()
            .MinimumLevel.Override("System", LogEventLevel.Error)
            .MinimumLevel.Override("Microsoft", LogEventLevel.Error)
            .Enrich.FromLogContext()
            .WriteTo.Debug()
            .WriteTo.Console()
            .WriteTo.Async(x => x.File("logs"));
}
```

And then you can initialize this in your `Main` method, like this:
```cs
public static async Task<int> Main(string[] args)
{
    try
    {
        GlobalSerilog.Configure(); // The VERY FIRST thing our application does is configure a logger

        using var host = CreateHostBuilder(args).Build();
        await host.RunAsync();

        return 0;
    }
    catch (Exception e)
    {
        GlobalSerilog.GetLogger().LogCritical(e, "Unhandled Exception");
        return 1;
    }
    finally
    {
        GlobalSerilog.Shutdown();
    }
}
```

Once you have the above two pieces in place, you can then use it like this:
```cs
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((context, builder) =>
        {
            builder.LogFileLoadExceptions(GlobalSerilog.GetLogger); // Here we reference our global static logger via a method group reference
        })
        .ConfigureLogging(loggingBuilder =>
        {
            loggingBuilder.ClearProviders();
        })
        .UseSerilog((context, configuration) =>
        {
            configuration.Configure(); // Here we configure the IoC logger for the rest of the application
        });
```

**Comment by eobeda** [comment]
Thanks I’ll try your suggestion when I get back to my machine.

-- Ed

**Comment by eobeda** [comment]
Hi,

Thanks for the directions.  Since I had been trying out
Serilog's CreateBootstrapLogger method......
see: https://nblumhardt.com/2020/10/bootstrap-logger/

I have the Serilog's global *Log *at hand. Combining your logic and some
other stuff I am trying out the bolded code below to set the logger.

             .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    Environment.ExitCode = 800;

                    config.Sources.Clear();

                    config
                      .SetBasePath(Directory.GetCurrentDirectory())
                      .AddJsonFile("appsettings.json", optional: false,
reloadOnChange: true)

.AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")
?? "Production"}.json", optional: true)
                      .AddEnvironmentVariables();








*config.LogFileLoadExceptions((type) =>                    {
        // Defaults to the static Log.Logger                        using
(var logfactory = new Serilog.Extensions.Logging.SerilogLoggerFactory())
                    {                            return
logfactory.CreateLogger(type?.FullName);                        }
          });*

I'll let you know if this breaks down once I start testing .

Bye and keep up the coding. :)
Ed

**Comment by shaynevanasperen** [comment]
Thanks. Shall I close this issue then?

**Comment by eobeda** [comment]
Sure close it.
Thanks again for the help

-- Ed
